### ISSUE TITLE
Create a Notebook file, run a gbif query

### ISSUE THREAD

**Issue by jeremymcwilliams** [BiodiversityDataScienceCorp/workflow-test#3]
@jcoliver can you do this on branch 2 (to be created in just sec)?

![bitmoji](https://sdk.bitmoji.com/render/panel/cf17d0ee-312b-4d8f-8020-3af37bc2702b-53bb3eb7-7591-4e3c-bff5-4625cda68522-v1.png?transparent=1&palette=1&width=246)

**Comment by jcoliver** [comment]
Indeed. Working on it.

**Comment by jeremymcwilliams** [comment]
Sure, that sounds perfect (no rush).

**Comment by jcoliver** [comment]
Woo-hoo! Pull Request #4 submitted!
